### ISSUE TITLE
[CRASH] Crash while initializing the sdk

### ISSUE THREAD

**Issue by BaptisteRFoxIntel** [Netvent/appsamurai-adsdk-android#1]
Hi,
We are experiencing several crashes.

SDK Version : `1.0.3`

Here's the stacktrace : 

```
Fatal Exception: java.lang.NoSuchMethodError: No static method createAsync(Landroid/os/Looper;)Landroid/os/Handler; in class Landroid/os/Handler; or its super classes (declaration of 'android.os.Handler' appears in /system/framework/framework.jar)
       at androidx.arch.core.executor.DefaultTaskExecutor.createAsync(DefaultTaskExecutor.java:82)
       at androidx.arch.core.executor.DefaultTaskExecutor.postToMainThread(DefaultTaskExecutor.java:67)
       at androidx.arch.core.executor.ArchTaskExecutor.postToMainThread(ArchTaskExecutor.java:101)
       at androidx.lifecycle.LiveData.postValue(LiveData.java:291)
       at androidx.lifecycle.MutableLiveData.postValue(MutableLiveData.java:45)
       at androidx.work.impl.OperationImpl.setState(OperationImpl.java:62)
       at androidx.work.impl.OperationImpl.<init>(OperationImpl.java:43)
       at androidx.work.impl.utils.EnqueueRunnable.<init>(EnqueueRunnable.java:77)
       at androidx.work.impl.WorkContinuationImpl.enqueue(WorkContinuationImpl.java:182)
       at androidx.work.impl.WorkManagerImpl.enqueue(WorkManagerImpl.java:336)
       at androidx.work.WorkManager.enqueue(WorkManager.java:214)
       at com.ppsmr.attribution.attributionsdk.a$a.a(a.java:25)
       at com.ppsmr.attribution.attributionsdk.AttributionSDK$Instance.initialize(AttributionSDK.java:1)
       at io.coco.android.App.onCreate(App.java:83)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5776)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1668)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:172)
       at android.app.ActivityThread.main(ActivityThread.java:6590)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by yigcal** [comment]
Hi @BaptisteRFoxIntel ,

Could you please send us the following information for your app:
- compileSdkVersion
- minSdkVersion
- targetSdkVersion
- Device information which received this exception (if you have)

Thank you

**Comment by BaptisteRFoxIntel** [comment]
Hi,
Seems I chose the wrong repo, we are using the attribution sdk (https://github.com/Netvent/as-attribution-android)
I can start updating to the last version 1.0.9, don't you maintain a changelog of your different releases ?

- compileSdkVersion 29
- minSdkVersion 17
- targetSdkVersion 29

Device information which received this exception (if you have)

```Brand: samsung
Model: Galaxy A7(2017)
Orientation: Portrait
RAM free: 1.85 GB
Disk free: 47.45 GB
Version: 9
Orientation: Portrait
Rooted: No
```

Thanks

**Comment by yigcal** [comment]
Hi,

We have just released version 1.0.10 for Android. You can start updating to this version. We have started to maintain the release notes starting from version 1.0.9 and we will complete the notes for the previous versions as soon as possible. You can find the latest version number and release notes in https://github.com/Netvent/as-attribution-android. 

We will investigate the reason of this exception. Thanks for the details.

Please let us know if you encounter any other problems.
Thanks

**Comment by BaptisteRFoxIntel** [comment]
Will do, thank you !
