### ISSUE TITLE
[CRASH] 

### ISSUE THREAD

**Issue by BaptisteRFoxIntel** [Netvent/appsamurai-adsdk-android#2]
SDV Version : `1.0.3`

Here's the stacktrace : 
```
Caused by java.nio.file.NoSuchFileException: /data/user/0/io.coco.android/files/appsamurai/custom_events/aggregation/AGG_aHR0cHM6Ly9wbGF5Lmdvb2dsZS5jb20vc3RvcmUvYXBwcy9kZXRhaWxzP2lkPWlvLmNsZWFuZm94LmFuZHJvaWR%2BMjMyMDF%2BZmx5LXlvdS1mb29scy1wZDE1NzAxMDU2NDA%3D_132_1570814881165.txt
       at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
       at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
       at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:115)
       at java.nio.file.Files.readAttributes(Files.java:1737)
       at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
       at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
       at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
       at java.nio.file.Files.walkFileTree(Files.java:2706)
       at java.nio.file.Files.walkFileTree(Files.java:2742)
       at com.ppsmr.attribution.attributionsdk.util.c.a(c.java:42)
       at com.ppsmr.attribution.attributionsdk.b.b$b.invoke(b.java:4)
       at com.ppsmr.attribution.attributionsdk.b.b.a(b.java:31)
       at com.ppsmr.attribution.attributionsdk.b.c$b.onResponse(c.java:3)
       at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Comment by yigcal** [comment]
Hi @BaptisteRFoxIntel ,

This issue is resolved in version 1.0.4, currently our latest version is 1.0.9. You can see the latest version of our android sdk from:

https://github.com/Netvent/as-attribution-android

Thank you
